# Generated by Django 3.2 on 2021-04-27 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='readers',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
