# Generated by Django 3.2 on 2021-04-30 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20210430_1305'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=20)),
                ('teacer_subject', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='students',
            old_name='DOB',
            new_name='student_DOB',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='id',
            new_name='student_id',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='name',
            new_name='student_name',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='subjects',
            new_name='student_subjects',
        ),
    ]
