# Generated by Django 3.2 on 2021-04-30 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20210430_1323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teachers',
            old_name='teacer_subject',
            new_name='teacher_subject',
        ),
    ]
